/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package telas;

import java.util.List;
import javax.swing.event.ListSelectionEvent;
import javax.swing.event.ListSelectionListener;
import javax.swing.table.DefaultTableModel;
import model.bean.Alunos;
import model.dao.AlunosDAO;
import raven.toast.Notifications;

/**
 *
 * @author Senai
 */
public final class TelaEditar extends javax.swing.JFrame {

    private DefaultTableModel tableModel;
    private int id = 0;
    private float recupe;
    String statusAprov;

    /**
     * Creates new form TelaEditar
     */
    public TelaEditar() {
        initComponents();
        leitura();
        Notifications.getInstance().setJFrame(this);
        tblAlunos.getSelectionModel().addListSelectionListener(new ListSelectionListener() {
            @Override
            public void valueChanged(ListSelectionEvent e) {
                int setar = tblAlunos.getSelectedRow();
                if (setar >= 0) {
                    String statusAprov;
                    id = (int) tblAlunos.getModel().getValueAt(setar, 0);
                    recupe = (float) tblAlunos.getModel().getValueAt(setar, 5);
                    statusAprov = (String) tblAlunos.getModel().getValueAt(setar, 6);
                    
                    txtNome.setText(tblAlunos.getModel().getValueAt(setar, 1).toString());
                    txtNota1.setText(tblAlunos.getModel().getValueAt(setar, 2).toString());
                    txtNota2.setText(tblAlunos.getModel().getValueAt(setar, 3).toString());
                    txtRecu.setText(tblAlunos.getModel().getValueAt(setar, 5).toString());
                    if (statusAprov.equals("Reprovado")) {
                        txtNota1.setEditable(false);
                        txtNota2.setEditable(false);
                        txtRecu.setEditable(true);
                    } else {
                        txtNota1.setEditable(true);
                        txtNota2.setEditable(true);
                        txtRecu.setEditable(false);
                    }
                    
                    if(recupe > 0){
                        txtNota1.setEditable(false);
                        txtNota2.setEditable(false);
                        txtRecu.setEditable(false);
                    }
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblAlunos = new javax.swing.JTable();
        lblVoltar = new javax.swing.JLabel();
        btnEditar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNome = new javax.swing.JTextField();
        txtNota1 = new javax.swing.JTextField();
        txtNota2 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtRecu = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tblAlunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID ALUNO", "NOME", "NOTA 1", "NOTA 2", "MEDIA", "RECUPERAÇÃO", "STATUS", "DISCIPLINA"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tblAlunos);
        if (tblAlunos.getColumnModel().getColumnCount() > 0) {
            tblAlunos.getColumnModel().getColumn(0).setMaxWidth(70);
            tblAlunos.getColumnModel().getColumn(2).setMaxWidth(65);
            tblAlunos.getColumnModel().getColumn(3).setMaxWidth(65);
            tblAlunos.getColumnModel().getColumn(4).setMaxWidth(65);
            tblAlunos.getColumnModel().getColumn(5).setMaxWidth(150);
            tblAlunos.getColumnModel().getColumn(6).setMaxWidth(75);
            tblAlunos.getColumnModel().getColumn(7).setMaxWidth(85);
        }

        lblVoltar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagens/icons8_back_to_30px.png"))); // NOI18N
        lblVoltar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblVoltar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblVoltarMouseClicked(evt);
            }
        });

        btnEditar.setText("EDITAR");
        btnEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEditarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("LISTA DE ALUNOS");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel2.setText("NOME");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("NOTA 1");

        txtNota1.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        txtNota2.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("NOTA 2");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel5.setText("RECUPERAÇÂO");

        txtRecu.setHorizontalAlignment(javax.swing.JTextField.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEditar, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 376, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, 45, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtRecu, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 1, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblVoltar)
                            .addGap(259, 259, 259)
                            .addComponent(jLabel1)
                            .addGap(0, 291, Short.MAX_VALUE))
                        .addComponent(jScrollPane1))
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addComponent(btnEditar)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(txtNota2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(txtNota1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(txtRecu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(292, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(lblVoltar)
                        .addComponent(jLabel1))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 76, Short.MAX_VALUE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 270, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap()))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void lblVoltarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblVoltarMouseClicked
        TelaLista objTelaLista = new TelaLista();
        objTelaLista.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_lblVoltarMouseClicked

    private void btnEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEditarActionPerformed
        Alunos objAluno = new Alunos();
        boolean bool;
        String status;
        if (txtNome.getText().isEmpty() || txtNota1.getText().isEmpty() || txtNota2.getText().isEmpty()) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, "SELECIONE UM CAMPO DA TABELA!");
            return;
        }
        try {
            boolean aprovado = false;
            String nome = txtNome.getText();
            float recuperacao = Float.parseFloat(txtRecu.getText());
            float nota1 = Float.parseFloat(txtNota1.getText());
            float nota2 = Float.parseFloat(txtNota2.getText());
            float media = (nota1 + nota2) / 2;
            if (recuperacao >= 7) {
                aprovado = true;
            }

            if (media >= 7) {
                aprovado = true;
            }

            objAluno.setNomeCompleto(nome);
            objAluno.setNota1(nota1);
            objAluno.setNota2(nota2);
            objAluno.setMedia(media);
            objAluno.setRecuperacao(recupe);
            objAluno.setAprovado(aprovado);
            objAluno.setIdAluno(id);

            AlunosDAO alunosDao = new AlunosDAO();
            alunosDao.alterarCampo(objAluno);
            limparCampos();
            leitura();
            id = 0;
            statusAprov = "";
        } catch (NumberFormatException e) {
            Notifications.getInstance().show(Notifications.Type.ERROR, Notifications.Location.TOP_CENTER, "OS VALORES DO CAMPO NOTA SÃO INVALIDOS!");
        }
    }//GEN-LAST:event_btnEditarActionPerformed

    public void leitura() {
        boolean bool;
        String status;
        tableModel = (DefaultTableModel) tblAlunos.getModel();
        tableModel.setNumRows(0);
        AlunosDAO alunosDao = new AlunosDAO();
        List<Alunos> alunos = alunosDao.leitura();

        for (Alunos objAlunos : alunos) {
            bool = objAlunos.isAprovado();
            if (bool == false) {
                status = "Reprovado";
            } else {
                status = "Aprovado";
            }
            Object[] rowData = {objAlunos.getIdAluno(), objAlunos.getNomeCompleto(), objAlunos.getNota1(), objAlunos.getNota2(), objAlunos.getMedia(), objAlunos.getRecuperacao(), status, objAlunos.getDisciplina()};
            tableModel.addRow(rowData);
        }
    }

    public void limparCampos() {
        txtNome.setText("");
        txtNota1.setText("");
        txtNota2.setText("");
        txtRecu.setText("");
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TelaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TelaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TelaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TelaEditar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TelaEditar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnEditar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblVoltar;
    private javax.swing.JTable tblAlunos;
    private javax.swing.JTextField txtNome;
    private javax.swing.JTextField txtNota1;
    private javax.swing.JTextField txtNota2;
    private javax.swing.JTextField txtRecu;
    // End of variables declaration//GEN-END:variables
}
